### ISSUE TITLE
Clarify potential stuck cluster

### ISSUE THREAD

**Issue by benjimin** [bottlerocket-os/bottlerocket-project-website#405]
The current docs suggest fragile behaviour, and particularly, the choice of wording e.g. "_may_ [not _will_] _become stuck_" implies unpredictableness (which is a discouragement to adoption because nobody wants their production clusters to have intermittent problems that are hard to replicate when debugging):

> The bottlerocket update operator only installs updates on one node at a time. If a node's update becomes stuck, it **can prevent** the operator from proceeding with **updates across the cluster**. [..] It is possible to mistakenly configure a Kubernetes cluster in such a way that a Pod can never be deleted while still maintaining the conditions of a PDB. In this case, **the operator may become stuck** waiting for the PDB to allow an eviction to proceed. Similarly, if the Node in question is repeatedly encountering issues while updating, it may cause updates across the cluster to become stuck.

Typically, replacing nodes in a dynamic cluster might involve cordoning the old nodes (so that future pods only get scheduled to updated nodes) and some combination of draining nodes or rolling restarts of deployments etc (so that pods on old nodes get terminated while replacement pods are created on new nodes). This process can be hindered for many reasons, for example: orphan pods without replicating controllers have to be discarded, PDBs may warn or warrant overriding, the cluster autoscaler pod might get killed before it initiates provisioning of a suitable node for itself to be rescheduled to, etc. I think the docs should be clearer about about: what strategy brupop follows, what factors do and don't interfere, how it behaves if impacted, and how to detect and remediate. For example, it would be great if the docs made obvious the answers to:

- If I have _some_ pods that are intended to be long-lived (e.g. interactive single-user JupyterHub sessions) and I use PDBs to forbid disruption to those, it's unclear from the docs whether or not brupop can still _always_ be relied upon to update the rest of the nodes in the cluster as early as possible? (In other words, does a hold-up on one host cause the updating of _other_ nodes to stall, and if so is this a bug that will be fixed soon?)
- Are there any deadlines that can be configured, so that brupop will force updates of _all_ nodes without delay (overriding PDBs etc as necessary) when the update becomes overdue (perhaps depending on the severity rating of the patches, and ideally at a schedulable hour of night)?
- If my cluster hosts some dynamic workloads that cannot be disrupted, will brupop ensure the host nodes _do_ get updated as soon as those original pods finish (and will it block similar pods from starting on that same host before the update, to avoid perpetuating the delay)? Moreover, if multiple nodes have issues blocking immediate updates, will brupop cordon all of them simultaneously (in parallel), and resume updates in whatever order the nodes become unblocked (asynchronously rather than sequentially)?
- Does brupop function exclusively be removing pods? For example, a rolling restart of a deployment will typically (e.g. for less than 4 replicas) cause new replicas to be readied _before_ any old pods are removed, and this kind of strategy can help maintain minimum availability during node replacement. Is brupop able to trigger transient scale ups (rather than transient scale downs) to achieve workload migrations without needing to violate PDBs?

**Comment by stockholmux** [comment]
@benjimin I added a whole load of documentation as a [PR](https://github.com/bottlerocket-os/bottlerocket-project-website/pull/419) for bottlerocket.dev. Feel free to give it a read. 

I think the new docs address most of your questions indirectly, but if you think they need a direct answer, I'm glad to throw a FAQ item in.

**Comment by benjimin** [comment]
Thanks @stockholmux 

So from this I conclude that:
* `brupop` is not intended to be used for dynamically scaled clusters (i.e., when existing nodes can also be replaced as easily as upgraded).
* If the upgrade of a node stalls or gets delayed for any reason (such as a pod disruption budget) then `brupop` just waits (not commencing upgrade to any further nodes) and the cluster upgrade is not guaranteed to ever complete.
* `brupop` relies simply on the kubernetes `drain` API for releasing a node from service.

These aren't exactly the answers I was hoping for (it doesn't sound suited to my use-case) but the extra clarity is very helpful (for being able to assess and to calibrate expectations more quickly).

**Comment by stockholmux** [comment]
Hey @benjimin 

Thanks for reading over the PR. Some of your conclusions are accurate, some are not, so that shows some room for improvement in the docs.

Let me directly address the conclusions:

> brupop is not intended to be used for dynamically scaled clusters (i.e., when existing nodes can also be replaced as easily as upgraded).

**Somewhat correct:** Brupop is intended for situations where you have a need to maintain instances instead of node-replacement. Dynamically scaling the cluster is orthogonal to how updates are managed: Brupop's controller will always push instances towards the most recent version. I know there are folks using Brupop because they philosophically don't like node replacement (they view in-place updating as less complex operation, but that's debatable). The project doesn't take a stance.

> If the upgrade of a node stalls or gets delayed for any reason (such as a pod disruption budget) then brupop just waits (not commencing upgrade to any further nodes) and the cluster upgrade is not guaranteed to ever complete.

**That's not correct.** Each node is independently pushed towards the most recent version. PDB can stall updates in a corner cases though - in a situation where you PDB is set to disallow *any* pod removal. [Pod Disruption Budgets are even part of the integration testing suite](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/integ/src/pods-template.yaml#L72-L80).

> brupop relies simply on the kubernetes drain API for releasing a node from service.

**Correct**: Brupop doesn't do anything extraordinary to drain the nodes.

It would be immediately helpful to sharpen the docs if you could tell me where you drew the first two conclusions? I'm glad to re-write those or provide more direct answers.
